// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://pmcuyiwuobhqexbpkgnd.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InBtY3V5aXd1b2JocWV4YnBrZ25kIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDgyMjQ0NjIsImV4cCI6MjA2MzgwMDQ2Mn0.1HF6NS5FOMNcj8YmzFn_V3l6HJNczjbN8zVvTPM1iDc";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);